### 新增记录

POST http://localhost:3000/api/v1/record
Content-Type: application/json

{
  "content": "中百超市买老干妈",
  "amount": "9.8",
  "tagId": 1
}


### 获取标签

GET http://localhost:3000/api/v1/tag?name=红包
Accept: application/json

### 删除标签

DELETE http://localhost:3000/api/v1/tag/3
Accept: application/json

### 编辑标签
PATCH http://localhost:3000/api/v1/tag/3
Content-Type: application/json

{
  "name": "红包",
  "icon": "red",
  "type": 1
}

### 新建标签

POST http://localhost:3000/api/v1/tag
Content-Type: application/json

{
  "name": "餐饮",
  "icon": "repast",
  "type": 0
}


### 用户注销

POST http://localhost:3000/api/v1/user/logout
Content-Type: application/json

### 用户登录

POST http://localhost:3000/api/v1/user/login
Content-Type: application/json

{
  "username": "cheng",
  "password": "123456"
}

### 注册用户

POST http://localhost:3000/api/v1/user/register
Content-Type: application/json

{
  "username": "cheng",
  "password": "123456"
}
